design:
  background-pink_color: '#EDCEC1'
  white_color: 'white'
  bright-yellow_color: '#F8C361'
  mustard-yellow_color: '#E7CC7C'
  orange_color: '#FF9B51'
  pink_color: '#FE9793'
  peach_color: '#E49A7B'
 