technical:
  google-analytics-embed:
  google-fonts-embed:
  stuff-for-head-embed:
  body-scripts-embed:
  cookie-script-banner:
  tracking-scripts-after-cookie-acceptance-embed:
social-media:
  instagram:
  youtube:
  facebook:
design:
  background-pink_color: '#edcec1'
  white_color: '#ffffff'
  bright-yellow_color: '#f8c361'
  mustard-yellow_color: '#e7cc7c'
  orange_color: '#ff9b51'
  pink_color: '#fe9793'
  peach_color: '#e49a7b'
  featured_text: "'Gill Sans', 'Gill Sans MT', Calibri, 'Trebuchet MS', sans-serif"
  regular_text: "'Segoe UI', Tahoma, Geneva, Verdana, sans-serif"