technical:
  google-analytics:
social-media:
  instagram:
  youtube:
  facebook:
design:
  background-pink_color: '#edcec1'
  white_color: '#ffffff'
  bright-yellow_color: '#f8c361'
  mustard-yellow_color: '#e7cc7c'
  orange_color: '#ff9b51'
  pink_color: '#fe9793'
  peach_color: '#e49a7b'