design:
  background-pink-color_color: '#EDCEC1;'
  white-color_color: 'white;'
  bright-yellow-color_color: '#F8C361;'
  mustard-yellow-color_color: '#E7CC7C;'
  orange-color_color: '#FF9B51;'
  pink-color_color: '#FE9793;'
  peach-color_color: '#E49A7B;'
 